# Generated by Django 3.0 on 2025-10-27 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0002_recreate_address_model'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[migrations.AlterModelTable(
                name='address',
                table='oc_lettings_site_address',
            ),
            ],
            database_operations=[],
        )
    ]
