# Generated by Django 3.0 on 2025-10-27 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0002_recreate_address_model'),
        ('oc_lettings_site', '0003_delete_letting'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Address',
                ),
            ],
            database_operations=[],
        )
    ]
